bank_project/bank_app/urls.py
from django.urls import path
from . import views

app_name = 'bank_app'

urlpatterns = [
        path('', views.index, name='index'),
        path('staff_dashboard/', views.staff_dashboard, name='staff_dashboard'),
        path('user_dashboard/', views.user_dashboard, name='user_dashboard'),
        path('create', views.create, name='create'),
        path('createaccount', views.createaccount, name='createaccount'),
        path('details/<int:pk>', views.details, name='details'),
        path('transfer', views.transfer, name='transfer'),
        ]

bank_project/bank_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('bank_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bank_project/bank_app/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
# from phonenumber_field.modelfields import PhoneNumberField
import uuid
from django.db.models import Sum
from django.db.models.functions import Coalesce
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError

class Customer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    phone = models.CharField(max_length=8, blank=True)
    RANK_CHOICES = [('G', 'Gold'), ('S', 'Silver'), ('B', 'Basic')]
    rank = models.CharField(max_length=1, choices=RANK_CHOICES, blank='B')
    def __str__(self):
        return f"{self.user}"

class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
 #   account_number = models.ChatField(max_length=100, blank=True, unique=True, default=uuid.uuid4)
    account_number = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    def __str__(self):
        return f"{self.account_number}"

    @property
    def balance(self):
        #if Ledger.objects.filter(account=self).aggregate(Sum('transaction'))
    #rows = Ledger.objects.filter(account=self)
   # total_balance = rows.aggregate(Sum('transaction')) if rows else 0
        return Ledger.objects.filter(account=self).aggregate((Sum('transaction'))) if Ledger.objects.filter(account=self) else 0
     #    return Ledger.objects.filter(account=self).annotate(total=Coalesce(Sum('transaction'), 0))
    #    return total_balance

class Uid(models.Model):
    pass

class Ledger(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    transaction = models.DecimalField(decimal_places=2, max_digits=12)
    ref = models.ForeignKey(Uid, on_delete=models.CASCADE)
    transaction_date = models.DateTimeField(auto_now_add=True, blank=True)


# Create your models here.

bank_project/bank_app/forms.py
from django import forms
from django.core.validators import RegexValidator, MinValueValidator
from .models import Customer, User, Account
from django.core.exceptions import ValidationError

# class CreateNewCustomer(forms.Form):
 #   firstName = forms.CharField(label="First Name", max_length=200)
  #  lastName = forms.CharField(label="Last Name", max_length=200)
   # email = forms.EmailField(label="Email")

   # rank = forms.ChoiceField(choices=Customer.RANK_CHOICES, widget=forms.RadioSelect)


class CreateNewCustomer(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password', 'email']
        labels = {'username':'Username', 'first_name':'First Name', 'last_name':'Last Name', 'password':'Password', 'email':'Email'}

class AddCustomerInfo(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['rank', 'phone']
        labels = {'rank':'Rank', 'phone':'Phone number'}

class CreateNewAccount(forms.Form):
    customer_id = forms.IntegerField(label="Customer ID")


class MakeTransfer(forms.Form):
        from_account = forms.CharField(label='From account', max_length=200)
        to_account = forms.CharField(label='To account', max_length=200)
        amount = forms.DecimalField(label='amount', decimal_places=2, max_digits=12, min_value='0.01')

bank_project/bank_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Customer, Account, Ledger, Uid
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User
from .forms import CreateNewCustomer, CreateNewAccount, MakeTransfer, AddCustomerInfo
from django.db import transaction

@login_required
def index(request):
    if request.user.is_staff:
        return HttpResponseRedirect('staff_dashboard/')
    else:
        return HttpResponseRedirect('user_dashboard/')


@staff_member_required
def staff_dashboard(request):
    users = User.objects.all()
    customers = Customer.objects.all()
    accounts = Account.objects.all()
    context = {
            'users': users,
            'customers': customers,
            'accounts': accounts
            }
    return render(request, 'bank_app/dashboard.html', context)


@login_required
def user_dashboard(request):
    customer = Customer.objects.filter(user=request.user)
    accounts = Account.objects.filter(user=request.user)
    context = {
            'customer': customer,
            'accounts': accounts
            }
    return render(request, 'bank_app/index.html', context)


def create(request):
    if request.method == 'POST':
        filled_form = CreateNewCustomer(request.POST)
        rank_phone_form = AddCustomerInfo(request.POST)

        if filled_form.is_valid():

            note = 'Customer profile for %s %s was successfully created!' %(filled_form.cleaned_data['first_name'], filled_form.cleaned_data['last_name'],)

            new_customer_form = CreateNewCustomer()
            new_rank_phone_form = AddCustomerInfo()
            context = {
                'new_customer_form':new_customer_form,
                'new_rank_phone_form':new_rank_phone_form,
                'note':note
                }
            username = request.POST['username']
            first_name = request.POST['first_name']
            last_name = request.POST['last_name']
            password = request.POST['password']
            email = request.POST['email']
            rank = request.POST['rank']
            phone = request.POST['phone']

            try:
                 ins = User(username=username, first_name=first_name, last_name=last_name, email=email, password=password)
                 ins.save()

                 user = User.objects.get(username=username)

                 rank_ins = Customer(user=user, rank=rank, phone=phone)
                 rank_ins.save()

            except Exception as e:
                 print(e)

            return render(request, 'bank_app/create.html', context)

    else:
        customer_form = CreateNewCustomer()
        extra_form = AddCustomerInfo()

        context = {
            'customer_form':customer_form,
            'extra_form':extra_form
             }
        return render(request, 'bank_app/create.html', context)



def createaccount(request):

    if request.method=="POST":
        customer_id = request.POST["customer_id"]
        account = Account()
        account.save()
    account_form = CreateNewAccount()

    context = {
        'account_form':account_form,
            }

    return render(request, 'bank_app/create_account.html', context)


def details(request, pk):
    account_number = Account.objects.get(pk=pk)
    transactions = Ledger.objects.filter(account=account_number).order_by('-transaction_date')
    context = {
        'account_number':account_number,
        'transactions':transactions,
            }
    return render(request, 'bank_app/details.html', context)

def transfer(request):
    if request.method=="POST":
        with transaction.atomic():
            from_account = request.POST['from_account']
            if Account.objects.get(account_number=from_account):
                to_account = request.POST['to_account']
                if Account.objects.filter(account_number=to_account):
                    amount = int(request.POST['amount'])
                    uid = Uid()
                    uid.save()
                    Ledger.objects.create(account=Account.objects.get(account_number=from_account), transaction=amount*-1, ref=Uid.objects.last())
                    Ledger.objects.create(account=Account.objects.get(account_number=to_account), transaction=amount, ref=Uid.objects.last())
  #accounts = Account.objects.filter(user=request.user)
  #accounts_numbers=accounts.values_list('account_number')
    transfer_form = MakeTransfer()
    context = {
        'transfer_form':transfer_form,
    #    'accounts':accounts,
     #   'accounts_numbers':accounts_numbers,
          }

    return render(request, 'bank_app/transfer.html', context)

bank_project/bank_app/templates/bank_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/holiday.css@0.9.8" />
   <title>Bank app</title>
</head>

<nav>
    <ul>
        <li><a href="{% url 'bank_app:index' %}">Home</a></li>
        {% if user.is_staff  %}
        <li><a href="{% url 'bank_app:create' %}">Create</a></li>
        <li><a href="{% url 'bank_app:createaccount' %}">Create account</a></li>
        {% endif %}
        <li><a href="{% url 'bank_app:transfer' %}">Transfer</a></li>
        <li>
            <span>{{ user }}</span>
            <ul>
                <!--TODO: create logout template-->
                <li><a href="{% url 'logout'  %}">Logout</a></li>
                <li><a href="{% url 'password_change'  %}">Password change</a></li>
            </ul>
        </li>
    </ul>
</nav>

<body>
    <!--   <h1>Bank app</h1> -->
    {% block header %}
    {% endblock %}
      {% block content %}
      {% endblock %}

      {% block footer %}
      {% endblock %}
</body>
</html>

bank_project/bank_app/templates/bank_app/create.html
{% extends "bank_app/base.html" %}

{% block title %} Create new Customer {% endblock %}
{% block header %} <h1>Create Customer</h1> {% endblock %}
{% block content %}
<form method="post" action="">
    {% csrf_token  %}

    {{ customer_form }}
    {% csrf_token  %}
    {{ extra_form }}
    <button type="submit", name="create">Create Customer</button>
</form>
<h2>{{ note }}</h2>

{% endblock %}

bank_project/bank_app/templates/bank_app/create_account.html
{% extends "bank_app/base.html" %}
12
11 {% block title %} Create new Customer account {% endblock %}
10
9 {% block content %}
8 Create Customer account
1 <form method="POST" action="">
    14      {% csrf_token %}
    1     {{ account_form }}
    2     <button type="submit">Create Account</button>
    3
    4 {% endblock %}

bank_project/bank_app/templates/bank_app/dashboard.html
{% extends "bank_app/base.html" %}


{% block content %}

<h3>STAFF details</h3>
<table>
    <tr>
<td>Username: {{ user.username }}</td>
<td>First name: {{ user.first_name }}</td>
<td>Last name: {{ user.last_name }}</td>
<td>Staff: {% if user.is_staff == 1 %} Yes {% else %} No {% endif %}</td>
    </tr>
</table>

<h3>All users</h3>
<table>
    {% for customer in customers  %}
    <tr>
        <td>First name: {{customer.user.first_name}}</td>
        <td>Last name: {{customer.user.last_name}}</td>
        <td>Rank: {{customer.rank}}</td>
        <td>Phone: {{customer.phone}}</td>
    </tr>
    {% endfor %}
</table>

<hr>

<h3>All accounts</h3>
<table>
    {% for account in accounts %}
    <tr>
        <td>Account owner: {{ account.user }}</td>
        <td>Account: {{account.account_number }}</td>
        <td>Balance: {% if account.balance.transaction__sum %}
            {{account.balance.transaction__sum|slice:"2:"}}
            {% else %}
            {{0}}
            {% endif %}
            DKK
        </td>
    </tr>
    {% endfor %}
</table>

<hr>

<button name="create" type='submit' onclick="location.href='{% url 'bank_app:create' %}'" >CREATE CUSTOMER ACCOUNT</button>

{% endblock %}

bank_project/bank_app/templates/bank_app/details.html
{% extends "bank_app/base.html" %}

{% block content %}
<h3>Account details</h3>
<h1>
    {% if account_number.balance.transaction__sum %}
        {{account_number.balance.transaction__sum}}
    {% else %}
        {{0}}
    {% endif %}
kr</h1>
<p>{{account_number}}</p>
<table>
    {% for transaction in transactions %}
    <tr>
        <tb>{{transaction.transaction_date}} - {{transaction.transaction}}</tb>
    </tr>
    {% endfor %}
</table>

{% endblock %}

bank_project/bank_app/templates/bank_app/index.html
{% extends "bank_app/base.html" %}

{% block header %}
<h1>Welcome {{ user }}</h1>
{% endblock %}
{% block content %}
<p>Username: {{ user.username }}</p>
<p>First name: {{ user.first_name }}</p>
<p>Last name: {{ user.last_name }}</p>
<p>Is staff? {% if user.is_staff == 1 %} "is staff" {% else %} "is not staff" {% endif %}</p>


<p>My accounts:</p>
<table>
    {% for account in accounts %}
    <tr>
        <td><h3>{% if account.balance.transaction__sum %}
            {{account.balance.transaction__sum|slice:"2:"}}
            {% else %}
            {{0}}
            {% endif %}
            DKK</h3>
    </td>
        <td> <a href="{% url 'bank_app:details' account.pk %}">{{account.account_number}}</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

bank_project/bank_app/templates/bank_app/transfer.html
{% extends "bank_app/base.html" %}

{% block title %} Create new Customer account {% endblock %}

{% block content %}
Make Money Transfer
<form method="post" action="">
    {% csrf_token  %}

    {{ transfer_form }}
    <button type="submit", name="create">Transfer</button>
</form>

{% endblock %}